services:
    sqld:
        deploy:
          resources:
            limits:
              cpus: "0.5"
              memory: 50M
        image: ghcr.io/tursodatabase/libsql-server:latest
        environment:
            SQLD_NODE: primary
        ports:
            - "8080:8080"
        networks:
            - my_network

networks:
    my_network: